# Generated by Django 4.2.25 on 2025-10-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estatura (m)'),
        ),
    ]
